export const EventType = {
  WORLD_TICK: "WORLD_TICK",
  AGENT_SPAWNED: "AGENT_SPAWNED",
  AGENT_DIED: "AGENT_DIED",
  CRISIS_STARTED: "CRISIS_STARTED",
  CRISIS_RESOLVED: "CRISIS_RESOLVED",
  REASONING_STARTED: "REASONING_STARTED",
  SKILL_PROPOSED: "SKILL_PROPOSED",
  SELF_EVAL_STARTED: "SELF_EVAL_STARTED",
  SELF_EVAL_RESULT: "SELF_EVAL_RESULT",
  SKILL_ACCEPTED: "SKILL_ACCEPTED",
  SKILL_REJECTED: "SKILL_REJECTED",
  AXL_MESSAGE: "AXL_MESSAGE",
  SKILL_TAUGHT: "SKILL_TAUGHT",
  SKILL_LEARNED: "SKILL_LEARNED",
  SKILL_INHERITED: "SKILL_INHERITED",
  ACTIVITY_STARTED: "ACTIVITY_STARTED",
  ACTIVITY_INTERRUPTED: "ACTIVITY_INTERRUPTED",
  FOOD_GATHERED: "FOOD_GATHERED",
  CURIOSITY_PEAK: "CURIOSITY_PEAK",
  HIDDEN_RULE_DISCOVERED: "HIDDEN_RULE_DISCOVERED",
  EPISODE_SAVED: "EPISODE_SAVED",
  EPISODE_LOADED: "EPISODE_LOADED",
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];

export type DomainEvent = {
  type: EventType;
  tick: number;
  actorId: string;
  payload: Record<string, unknown>;
  receiptHash?: string;
};
