export const EventType = {
  WORLD_TICK: "WORLD_TICK",
  AGENT_SPAWNED: "AGENT_SPAWNED",
  AGENT_DIED: "AGENT_DIED",
  CRISIS_STARTED: "CRISIS_STARTED",
  CRISIS_RESOLVED: "CRISIS_RESOLVED",
  CRISIS_EXPIRED: "CRISIS_EXPIRED",
  REASONING_STARTED: "REASONING_STARTED",
  SKILL_PROPOSED: "SKILL_PROPOSED",
  SELF_EVAL_STARTED: "SELF_EVAL_STARTED",
  SELF_EVAL_RESULT: "SELF_EVAL_RESULT",
  SKILL_ACCEPTED: "SKILL_ACCEPTED",
  SKILL_REJECTED: "SKILL_REJECTED",
  AXL_WHISPER: "AXL_WHISPER",
  AXL_BROADCAST: "AXL_BROADCAST",
  SKILL_TAUGHT: "SKILL_TAUGHT",
  SKILL_LEARNED: "SKILL_LEARNED",
  SKILL_INHERITED: "SKILL_INHERITED",
  FOOD_GATHERED: "FOOD_GATHERED",
  EPISODE_SAVED: "EPISODE_SAVED",
  EPISODE_LOADED: "EPISODE_LOADED",
  SKILL_ACCEPTED_FROM_PEER: "SKILL_ACCEPTED_FROM_PEER",
  SKILL_REJECTED_BY_PEER: "SKILL_REJECTED_BY_PEER",
  DEATH_WARNING: "DEATH_WARNING",
  AGENT_ACTION: "AGENT_ACTION",
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];

export type DomainEvent = {
  type: EventType;
  tick: number;
  actorId: string;
  payload: Record<string, unknown>;
  receiptHash?: string;
};

// Alias used by kernel-impl — both names refer to the same shape.
export type Event = DomainEvent;
