/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AgentMarketplace {
  export type ListingStruct = {
    tokenId: BigNumberish;
    sellerEngine: AddressLike;
    salePriceWei: BigNumberish;
    active: boolean;
    worldId: BytesLike;
  };

  export type ListingStructOutput = [
    tokenId: bigint,
    sellerEngine: string,
    salePriceWei: bigint,
    active: boolean,
    worldId: string
  ] & {
    tokenId: bigint;
    sellerEngine: string;
    salePriceWei: bigint;
    active: boolean;
    worldId: string;
  };
}

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "delist"
      | "getActiveListings"
      | "list"
      | "listings"
      | "nftContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Delisted" | "Listed" | "Sold"
  ): EventFragment;

  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "delist",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "list",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "list", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
}

export namespace DelistedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    sellerEngine: AddressLike,
    worldId: BytesLike,
    salePriceWei: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    sellerEngine: string,
    worldId: string,
    salePriceWei: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    sellerEngine: string;
    worldId: string;
    salePriceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoldEvent {
  export type InputTuple = [tokenId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [tokenId: bigint, buyer: string];
  export interface OutputObject {
    tokenId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;

  delist: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  getActiveListings: TypedContractMethod<
    [],
    [AgentMarketplace.ListingStructOutput[]],
    "view"
  >;

  list: TypedContractMethod<
    [tokenId: BigNumberish, salePriceWei: BigNumberish, worldId: BytesLike],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean, string] & {
        tokenId: bigint;
        sellerEngine: string;
        salePriceWei: bigint;
        active: boolean;
        worldId: string;
      }
    ],
    "view"
  >;

  nftContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "delist"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveListings"
  ): TypedContractMethod<[], [AgentMarketplace.ListingStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "list"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePriceWei: BigNumberish, worldId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean, string] & {
        tokenId: bigint;
        sellerEngine: string;
        salePriceWei: bigint;
        active: boolean;
        worldId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Delisted"
  ): TypedContractEvent<
    DelistedEvent.InputTuple,
    DelistedEvent.OutputTuple,
    DelistedEvent.OutputObject
  >;
  getEvent(
    key: "Listed"
  ): TypedContractEvent<
    ListedEvent.InputTuple,
    ListedEvent.OutputTuple,
    ListedEvent.OutputObject
  >;
  getEvent(
    key: "Sold"
  ): TypedContractEvent<
    SoldEvent.InputTuple,
    SoldEvent.OutputTuple,
    SoldEvent.OutputObject
  >;

  filters: {
    "Delisted(uint256)": TypedContractEvent<
      DelistedEvent.InputTuple,
      DelistedEvent.OutputTuple,
      DelistedEvent.OutputObject
    >;
    Delisted: TypedContractEvent<
      DelistedEvent.InputTuple,
      DelistedEvent.OutputTuple,
      DelistedEvent.OutputObject
    >;

    "Listed(uint256,address,bytes32,uint256)": TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;
    Listed: TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;

    "Sold(uint256,address)": TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
    Sold: TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
  };
}
